In [6]:
import pandas as pd
import numpy as np

from numpy.linalg import eigh
np.set_printoptions(linewidth=100)
# sample data from 
df = pd.read_csv('/Users/thanakrit.boo/Documents/Local Project/Python/FactorAnalysis/data.csv', index_col=0)

# Data

Five subjects who were trying on ski boots late on a Friday night in January were asked about the importance of each of four variables to their selection of a ski resort. The variables were cost of ski ticket (COST), speed of ski lift (LIFT), depth of snow (DEPTH), and moisture of snow (POWDER). Larger numbers indicate greater importance. The researcher wanted to investigate the pattern of relationships among the variables in an effort to understand better the dimensions underlying choice of ski area.

# Extraction

In [ ]:
corr = df.corr()
# Corr from cov, std
# df.cov()/(df.std().to_numpy().reshape(-1,1)@df.std().to_numpy().reshape(1,-1))
corr

COST      LIFT     DEPTH    POWDER
COST    1.000000 -0.952990 -0.055276 -0.129999
LIFT   -0.952990  1.000000 -0.091107 -0.036248
DEPTH  -0.055276 -0.091107  1.000000  0.990174
POWDER -0.129999 -0.036248  0.990174  1.000000

In [2]:
eigval, eigvec = eigh(corr)
display(eigval)
display(eigvec)

NameError: name 'corr' is not defined

In [10]:
# Re-arrage of correlation matrix from eigen value, eigen vector
re_composed_corr = eigvec@np.diag(eigval)@eigvec.T
display(re_composed_corr)

array([[ 1.        , -0.95299048, -0.05527555, -0.12999882],
       [-0.95299048,  1.        , -0.09110654, -0.03624823],
       [-0.05527555, -0.09110654,  1.        ,  0.99017435],
       [-0.12999882, -0.03624823,  0.99017435,  1.        ]])

In [14]:
# Split eigval into sqrt(np.diag(eigval))*sqrt(np.diag(eigval)), call
# eigvec@(np.diag(eigval)) = (unrotated) factor loading matrix
factor_loading = eigvec@np.diag(np.sqrt(eigval))
display(factor_loading)

array([[ 1.06574148e-03,  2.50503238e-02, -1.19272984e+00,  7.10572168e-01],
       [ 8.68512733e-04,  2.55570896e-02,  1.28870740e+00, -5.06344250e-01],
       [-2.85364944e-03,  1.04158724e-02, -6.25612168e-01, -1.26502720e+00],
       [ 3.00878236e-03, -6.37154046e-03, -5.42875736e-01, -1.30533335e+00]])

To represent the correlation matrix, with less number of factors.  
Use high value eigen value (and corresponding eigen vector), since higher eigen value, shown relation between factor and original correlation matrix.  
If choose only top 2 factor

In [72]:
top_eigval = eigval[:-3:-1] # re-order by top value first
top_eigval

array([2.0163051 , 1.94151381])

In [74]:
top_eigvec = eigvec[:,[3,2]] # re-order according to corresponding eigen val
top_eigvec

array([[ 0.35241302, -0.61432982],
       [-0.25112482,  0.66376422],
       [-0.6273987 , -0.32222906],
       [-0.6473888 , -0.27961467]])

In [75]:
top_corr = top_eigvec@np.diag(top_eigval)@top_eigvec.T
top_corr

array([[ 0.9831444 , -0.9701337 , -0.06147984, -0.12651171],
       [-0.9701337 ,  0.98255347, -0.09757925, -0.03253989],
       [-0.06147984, -0.09757925,  0.99526684,  0.99389478],
       [-0.12651171, -0.03253989,  0.99389478,  0.99685421]])

In [76]:
corr

COST      LIFT     DEPTH    POWDER
COST    1.000000 -0.952990 -0.055276 -0.129999
LIFT   -0.952990  1.000000 -0.091107 -0.036248
DEPTH  -0.055276 -0.091107  1.000000  0.990174
POWDER -0.129999 -0.036248  0.990174  1.000000

L

In [77]:
top_factor_loading = top_eigvec@np.diag(top_eigval)
top_factor_loading

array([[ 0.71057217, -1.19272984],
       [-0.50634425,  1.2887074 ],
       [-1.2650272 , -0.62561217],
       [-1.30533335, -0.54287574]])

__Interpretation__  
First factor high relation with `DEPTH` and `POWDER`, indicate the factor based on environment  
Second factor high relation with `COST` and `LIFT` , indicate the factor based on infrastructure  

# Orthogonal Rotation